language: ruby

bundler_args: "--binstubs --standalone --without documentation --path ../bundle"
script: "bundle exec rake test"
rvm:
  - 2.0.0
  - 2.1.9
  - 2.2.10
  - 2.3.7
  - 2.4.4
  - 2.5.1
notifications:
  email: false
